version: '3.8'

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: book-library-backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    restart: always

  frontend:
    build:
      context: ../book-library-frontend
      dockerfile: Dockerfile
    container_name: book-library-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
